version: '3.7'
services:
  mysql_db_container:
    image: mysql:latest
    container_name: mysqlPractica
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: comillas
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
      - ./empleados/empleados.sql:/empleados.sql
      - ./empleados/:/var/lib/mysql-files/
      - ./autobuses/CrearBD.sql:/CrearBD.sql
      - ./autobuses/:/root/Descargas/Autobuses
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080

volumes:
  mysql_db_data_container: